version: '3'
services:
 mysql:
   image: mysql:latest
   ports:
      - "3306:3306"
   container_name: mysql-docker
   network_mode: host
   environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: newDB
        MYSQL_USER: app_root
        MYSQL_PASSWORD: Root@123
 spring-movie:
   image: movie-app1
   build: MovieApp Test/
   restart: always
   network_mode: host
   container_name: movie-app
   depends_on:
       - mongo
   ports:
       - 8090:8090
   expose:
       - 8090
 spring-user:
   image: user-service1
   build: userservice/
   restart: always
   network_mode: host
   container_name: user-app
   depends_on:
       - mysql
   ports:
       - 8082:8082
   expose:
       - 8082
 spring-zuul:
   image: zuul1
   build: ZuulApiGateway/
   restart: always
   network_mode: host
   container_name: zuul-app
   depends_on:
       - spring-user
       - spring-movie
   ports:
       - 8080:8080
   expose:
       - 8080
 mongo:
   image: mongo:3.4-xenial
   ports:
      - "27017:27017"
   container_name: mongo-docker
   network_mode: host
    
 
